

default: control.png texatlas.png check.png icon.png
	cp control.png texatlas.png check.png icon.png ../assets

control.png: control.svg
	convert -background transparent control.svg control.png

texatlas.png: texatlas.svg
	convert -background transparent texatlas.svg texatlas.png

check.png: check.svg
	convert -background transparent check.svg check.png

icon.png: icon.svg
	convert -background transparent icon.svg icon.png
